// Code generated by mockery v2.13.1. DO NOT EDIT.

package tenant

import (
	context "context"
	ent "rental-porperty-management/ent"

	mock "github.com/stretchr/testify/mock"
)

// MockITenantRepo is an autogenerated mock type for the ITenantRepo type
type MockITenantRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, attributes
func (_m *MockITenantRepo) Create(c context.Context, attributes TenantRequest) (*ent.Tenant, error) {
	ret := _m.Called(c, attributes)

	var r0 *ent.Tenant
	if rf, ok := ret.Get(0).(func(context.Context, TenantRequest) *ent.Tenant); ok {
		r0 = rf(c, attributes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Tenant)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, TenantRequest) error); ok {
		r1 = rf(c, attributes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: c, serviceID
func (_m *MockITenantRepo) Delete(c context.Context, serviceID int) error {
	ret := _m.Called(c, serviceID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(c, serviceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, searchBy, sortBy, pageOffset, itemsPerPage
func (_m *MockITenantRepo) Get(ctx context.Context, searchBy string, sortBy string, pageOffset int, itemsPerPage int) ([]*ent.Tenant, error) {
	ret := _m.Called(ctx, searchBy, sortBy, pageOffset, itemsPerPage)

	var r0 []*ent.Tenant
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []*ent.Tenant); ok {
		r0 = rf(ctx, searchBy, sortBy, pageOffset, itemsPerPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.Tenant)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = rf(ctx, searchBy, sortBy, pageOffset, itemsPerPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: c, id
func (_m *MockITenantRepo) GetByID(c context.Context, id int) (*ent.Tenant, error) {
	ret := _m.Called(c, id)

	var r0 *ent.Tenant
	if rf, ok := ret.Get(0).(func(context.Context, int) *ent.Tenant); ok {
		r0 = rf(c, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Tenant)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, serviceID, r
func (_m *MockITenantRepo) Update(c context.Context, serviceID int, r TenantRequest) (*ent.Tenant, error) {
	ret := _m.Called(c, serviceID, r)

	var r0 *ent.Tenant
	if rf, ok := ret.Get(0).(func(context.Context, int, TenantRequest) *ent.Tenant); ok {
		r0 = rf(c, serviceID, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Tenant)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, TenantRequest) error); ok {
		r1 = rf(c, serviceID, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockITenantRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockITenantRepo creates a new instance of MockITenantRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockITenantRepo(t mockConstructorTestingTNewMockITenantRepo) *MockITenantRepo {
	mock := &MockITenantRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
